[package]
name = "otter-auth-client"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"

